development:
  dialect: postgres
  database: postgres
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ril_test?sslmode=disable"}}

production:
  dialect: postgres
  database: ril_production
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ril_production?sslmode=disable"}}
